; PlatformIO Project Configuration File
; Placa: RYMCU ESP32-S3 DevKitC-1

[platformio]
default_envs = rymcu-esp32-s3-devkitc-1

[env:rymcu-esp32-s3-devkitc-1]
platform = espressif32
board = rymcu-esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

build_flags = 
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_LOOP_STACK_SIZE=8192

lib_deps = 
    miguelbalboa/MFRC522
    bblanchon/ArduinoJson
    ; NO incluyas ninguna librería SD, usa la nativa